---
- name: register dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  
- name: add dotdeb default repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian.version }} all' state=present

- name: add dotdeb php repositories
  apt_repository: repo='deb http://packages.dotdeb.org {{ debian.version }}-php{{ php.version }} all' state=present

- name: add dotdeb php sources repositories
  apt_repository: repo='deb-src http://packages.dotdeb.org {{ debian.version }}-php{{ php.version }} all' state=present

- name: install php packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items: php.extensions

- name: activate extensions
  shell: php5enmod {{ item }}
  with_items: php.extensions