---
- name: install php packages
  apt: pkg={{ php.version }}-{{ item }} state=latest force=yes update_cache=yes
  with_items: php.extensions

- name: activate extensions
  shell: phpenmod {{ php.version }}-{{ item }}
  with_items: php.extensions
