---

- name: build a packages list
  set_fact:
    php_packages: "{{ 'php' + php.version + '-' + item }}"
  with_items: "{{ php.extensions }}"

- name: install php packages
  apt:
    name: "{{ php_packages }}"
    state: latest
    force: yes
    update_cache: yes

- name: activate extensions
  shell: phpenmod php{{ php.version }}-{{ item }}
  with_items: "{{ php.extensions }}"
