---

- name: build a packages list
  set_fact:
    php_packages: "{{ php_packages + [ 'php' + php.version|string + '-' + item ] }}"
  with_items: "{{ php.extensions }}"
  vars:
    php_packages: []

- name: install php packages
  apt:
    name: "{{ php_packages }}"
    state: latest
    force: yes
    update_cache: yes

- name: activate extensions
  shell: phpenmod {{ item }}
  with_items: "{{ php_packages }}"
