---
- name: install php packages
  apt:
    pkg: "{{ 'php' + php.version + '-' + php.extensions }}"
    state: latest
    force: yes
    update_cache: yes

- name: activate extensions
  shell: phpenmod php{{ php.version }}-{{ item }}
  with_items: "{{ php.extensions }}"
